In [1]:
import pandas as pd

In [2]:
file_path = "data/skill_builder_data.csv"
df = pd.read_csv(file_path)

/tmp/ipykernel_29887/55773193.py:2: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [3]:
# Step 1.1 - Remove questions without skill
df.dropna(subset=['skill_id'], inplace=True)

# Step 1.2 - Remove users with a single answer
df = df.groupby('user_id').filter(lambda q: len(q) > 1).copy()

# Step 2 - Enumerate skill id
# convert skill labels to integers starting from 0
df['skill'], _ = pd.factorize(df['skill_id'], sort=True)  # we can also use problem_id to represent exercises

In [4]:
df

,order_id,assignment_id,user_id,assistment_id,problem_id,original,correct,attempt_count,ms_first_response,tutor_mode,...,hint_total,overlap_time,template_id,answer_id,answer_text,first_action,bottom_hint,opportunity,opportunity_original,skill
0,33022537,277618,64525,33139,51424,1,1,1,32454,tutor,...,3,32454,30799,NaN,26,0,NaN,1,1.0,0
1,33022709,277618,64525,33150,51435,1,1,1,4922,tutor,...,3,4922,30799,NaN,55,0,NaN,2,2.0,0
2,35450204,220674,70363,33159,51444,1,0,2,25390,tutor,...,3,42000,30799,NaN,88,0,NaN,1,1.0,0
3,35450295,220674,70363,33110,51395,1,1,1,4859,tutor,...,3,4859,30059,NaN,41,0,NaN,2,2.0,0
4,35450311,220674,70363,33196,51481,1,0,14,19813,tutor,...,4,124564,30060,NaN,65,0,0.0,3,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459202,33150328,277900,85730,69050,128450,1,0,2,51594,tutor,...,4,130875,59998,NaN,0,0,NaN,12,12.0,122
459203,33150408,277900,85730,69042,128442,1,0,2,51016,tutor,...,4,102125,59998,NaN,3-Jul,0,NaN,13,13.0,122
459204,33150487,277900,85730,69056,128456,1,1,1,61547,tutor,...,4,61547,59998,NaN,2-May,0,NaN,14,14.0,122
459205,33150779,277900,85730,69046,128446,1,1,1,53890,tutor,...,4,53890,59998,NaN,10/-6,0,NaN,15,15.0,122
459206,33151098,277901,85730,69057,128457,1,0,4,181532,tutor,...,3,196844,60008,NaN,57/9,0,1.0,16,16.0,122

In [5]:
df['skill_with_answer'] = df['skill'] * 2 + df['correct']
df

,order_id,assignment_id,user_id,assistment_id,problem_id,original,correct,attempt_count,ms_first_response,tutor_mode,...,overlap_time,template_id,answer_id,answer_text,first_action,bottom_hint,opportunity,opportunity_original,skill,skill_with_answer
0,33022537,277618,64525,33139,51424,1,1,1,32454,tutor,...,32454,30799,NaN,26,0,NaN,1,1.0,0,1
1,33022709,277618,64525,33150,51435,1,1,1,4922,tutor,...,4922,30799,NaN,55,0,NaN,2,2.0,0,1
2,35450204,220674,70363,33159,51444,1,0,2,25390,tutor,...,42000,30799,NaN,88,0,NaN,1,1.0,0,0
3,35450295,220674,70363,33110,51395,1,1,1,4859,tutor,...,4859,30059,NaN,41,0,NaN,2,2.0,0,1
4,35450311,220674,70363,33196,51481,1,0,14,19813,tutor,...,124564,30060,NaN,65,0,0.0,3,3.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459202,33150328,277900,85730,69050,128450,1,0,2,51594,tutor,...,130875,59998,NaN,0,0,NaN,12,12.0,122,244
459203,33150408,277900,85730,69042,128442,1,0,2,51016,tutor,...,102125,59998,NaN,3-Jul,0,NaN,13,13.0,122,244
459204,33150487,277900,85730,69056,128456,1,1,1,61547,tutor,...,61547,59998,NaN,2-May,0,NaN,14,14.0,122,245
459205,33150779,277900,85730,69046,128446,1,1,1,53890,tutor,...,53890,59998,NaN,10/-6,0,NaN,15,15.0,122,245
459206,33151098,277901,85730,69057,128457,1,0,4,181532,tutor,...,196844,60008,NaN,57/9,0,1.0,16,16.0,122,244

In [6]:
feature_list = []
question_list = []
answer_list = []
seq_len_list = []

def get_data(series):
    feature_list.append(series['skill_with_answer'].tolist())
    question_list.append(series['skill'].tolist())
    answer_list.append(series['correct'].eq(1).astype('int').tolist())
    seq_len_list.append(series['correct'].shape[0])

df.groupby('user_id').apply(get_data)

/tmp/ipykernel_29887/2951026088.py:12: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('user_id').apply(get_data)

Empty DataFrame
Columns: []
Index: []